### ISSUE TITLE
Floki and html_sanitize_ex in the same project?

### ISSUE THREAD

**Issue by aphillipo** [rrrene/html_sanitize_ex#11]
Hello!  Thanks for this html sanitizing library, it's awesome and I'm using it a lot...

However I need Floki included as well for various reasons and that uses just the mochiweb_html package that only includes the html parser.  I can see their thinking for this but it causes problems with generating a release; all of the modules conflict:

==> Failed to build release:

```
Duplicated modules: 
    mochiweb_html specified in mochiweb and mochiweb_html
    mochiweb_charref specified in mochiweb and mochiweb_html
    mochiutf8 specified in mochiweb and mochiweb_html
    mochinum specified in mochiweb and mochiweb_html
```

You can find mochiweb_html here:

https://github.com/philss/mochiweb_html

I've decided that I'll ask Floki to change over to the full version of mochiweb but I'll leave this here for posterity.  Feel free to close this!  Thanks.

**Comment by aphillipo** [comment]
Okay so I'll close this and ask floki to use :mochiweb instead of :mochiweb_html - let's see if it's possible...

**Comment by ArturT** [comment]
Resolved in https://github.com/philss/floki/issues/68
