### ISSUE TITLE
stripping <script> tags leaves source code alone

### ISSUE THREAD

**Issue by haslinger** [rrrene/html_sanitize_ex#13]
`HtmlSanitizeEx.basic_html("<script>test</script>")` 

should probably return 

`""` 
and not 

`"test"`

**Comment by rrrene** [comment]
I see your point. So should we have two sets of tags: Those which are completely scrubbed and those which are merely removed? Because I don't want

```
HtmlSanitizeEx.basic_html("Hello <b>Stefan</b>!")
```

to return

```
"Hello !"
```

just because somebody used unnecessary formatting. WDYT?

**Comment by haslinger** [comment]
Ah - yes - right, maybe something like

`Meta.scrub_with_text("script")`

to explicitly declare in the scrubber, that you want to get rid of the text within the tag as well?

Btw, thanks for your awesome work here, I created an extra scubber based on basic_html without allowing img tags and it works nicely!

**Comment by jney** [comment]
hi there. this is an old issue, but i have a related need. i would like to remove non readable (and risky) tags and attributes, such as `<script>` and `<a href="javascript:alert('XSS');">` to avoid XSS attack. 
any solution there ?

**Comment by rrrene** [comment]
@jney That's exactly what `HtmlSanitizeEx` does :+1: I'm not sure what you are asking for?

**Comment by jney** [comment]
I'd like to keep the meaning of the text.

I'd like this text:

```html
<p>Hello <script>console.log('World')</script><span>Rene</span>.</p>
```
to be turned into:

```html
<p>Hello <span>Rene</span>.</p>
```

I want to keep the text, removing `javascript` and styles related tags and attributes.
Maybe is it about blacklist some tags, or something.

**Comment by rrrene** [comment]
As I said, this is intentional. But: you can easily write your own Scrubber using [`HtmlSanitizeEx.Scrubber.Meta`](https://github.com/rrrene/html_sanitize_ex/blob/c9b05d982e988a554b56b1f9ab40df89ae14a9cf/lib/html_sanitize_ex/scrubber/meta.ex) to suit your personal preference.

For the example you've given, you would just build off of the scrubber that suits you and add a single line:

```elixir
def scrub({"script", _attributes, _children}), do: nil
```

**Comment by rohanbhangui** [comment]
For those that are curious for an example:

```

defmodule MyModule.HtmlScrubber do
  alias HtmlSanitizeEx.Scrubber.Meta
  require HtmlSanitizeEx.Scrubber.Meta

  Meta.remove_cdata_sections_before_scrub()

  def scrub({"script", _attributes, _children}), do: ""
  def scrub({"script", _children}), do: ""

  Meta.strip_comments()

  Meta.allow_tag_with_these_attributes("p", ["style"])
  
  # other rules ....

  Meta.strip_everything_not_covered()
end


```


Usage:

```
def strip_tags(value) do
    value
    |> to_string()
    |> Scrubber.scrub(HtmlScrubber)
  end
```
