### ISSUE TITLE
HTML5 Options Strips <blockquote>

### ISSUE THREAD

**Issue by praveenperera** [rrrene/html_sanitize_ex#16]
The HTML5 sanitize scrubber option strips `<blockquote>` however the basic_html option does not. I was wondering if this was by design or if it was an oversight. If this was an oversight would you accept a PR with it added? I need to allow blockquotes as well as HTML5 elements in my webpage.

**Comment by rrrene** [comment]
Thx for the PR! :+1: 

Will make a release and update you shortly!

**Comment by praveenperera** [comment]
@rrrene Thanks for merging. I noticed that the html5 option was missing a few others that exist in the basic_html option. I will add them this week and submit a PR. Maybe release after that?

**Comment by rrrene** [comment]
Sure. But please do not add `"style"` to the list of attributes. It should be included in [this line](https://github.com/rrrene/html_sanitize_ex/blob/8c451972c85e0c0ecc775f63de986a08629c7654/lib/html_sanitize_ex/scrubber/html5.ex#L186).

**Comment by praveenperera** [comment]
@rrrene thanks I'll keep that in mind and I'll fix it in the blockquote line

**Comment by rrrene** [comment]
no need, already did :wink:
