### ISSUE TITLE
Multiple pass idea

### ISSUE THREAD

**Issue by sb8244** [rrrene/html_sanitize_ex#38]
I wanted to run this idea past you to look at a problem we ran into at work. We wanted to scrub a tags and remove any tags which ended up empty. So `<a href="not valid">okay</a>` would turn into `okay` rather than `<a>okay</a>`.

We did this by implementing a macro like: 

```
    defmacro strip_tag_that_has_no_scrubbed_attributes(tag_name) do
      quote do
        def scrub({unquote(tag_name), attributes, children}) do
          scrub_attributes(unquote(tag_name), attributes)
          |> case do
            [] ->
              children

            scrubbed ->
              {unquote(tag_name), scrubbed, children}
          end
        end

        defp scrub_attributes(unquote(tag_name), attributes) do
          Enum.map(attributes, fn attr ->
            scrub_attribute(unquote(tag_name), attr)
          end)
          |> Enum.reject(&is_nil(&1))
        end
      end
```

We ended up having to copy paste one of the Meta functions to make this work. One idea that I was waffling on is that if the Traversal took multiple passes and looked for a stable state, then you could write functions which handle a single part only. The cost is more traversals, but simpler thought process. For example, we could have a scrub function which scrubs the `href` tag of `a` links and another scrub function which removes a tags with empty attributes. The order of operations wouldn't matter in that case, then.

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.
