### ISSUE TITLE
whitespace truncated

### ISSUE THREAD

**Issue by smeevil** [rrrene/html_sanitize_ex#4]
Hi,

I noticed the following behaviour :

```
iex(1)> HtmlSanitizeEx.basic_html("This <b>is</b> <b>an</b> <i>example</i> of <u>space</u> eating.")
"This <b>is</b><b>an</b><i>example</i> of <u>space</u> eating."
```

The sanitiser is eating whitespace if directly followed by an other whitelisted tag. I would  expect the result to be :

```
"This <b>is</b> <b>an</b> <i>example</i> of <u>space</u> eating."
```

Gerard.

**Comment by rrrene** [comment]
Hi Gerard,

this is definitely a bug! Thx for reporting! :+1:

**Comment by smeevil** [comment]
I'm trying to investigate the origin.
It seems its related to mochiweb_html.

for example : 

```
test "It should conserve spaces between tags" do
    input ="<test>hello <b>world</b> <b>how</b> are you doing ?</test>"
    assert [{"test", [], ["hello ", {"b", [], ["world"]}, " ", {"b", [], ["how"]}, " are you doing ?"]}] = :mochiweb_html.parse(input)
end
```

returns 

```
match (=) failed
     code: [{"test", [], ["hello ", {"b", [], ["world"]}, " ", {"b", [], ["how"]}, " are you doing ?"]}] = :mochiweb_html.parse(input)
     rhs:  {"test", [], ["hello ", {"b", [], ["world"]}, {"b", [], ["how"]}," are you doing ?"]}
```

Here you can see it misses the " " between the b tags.

**Comment by smeevil** [comment]
I think this is the point of origin : https://github.com/mochi/mochiweb/blob/d024b4a5804fe4e0061c4ed2d1c52bdd168995e9/src/mochiweb_html.erl#L81

I'm really out of my comfort zone here though, but maybe we should forward this case to them, what do you think ?

**Comment by rrrene** [comment]
I investigated to that point as well and then ... went asleep. I concluded that since the `parse` function does not take a second parameter, is must be (a) intended behaviour or (b) a bug. 

But I am really outside my "comfort zone" here as well. My Erlang-Fu is weak. :disappointed:

**Comment by smeevil** [comment]
ok, something I just found : 

```
iex(1)> :mochiweb_html.parse("<html>just <b>an</b> <b>other</b> test</html>")
{"html", [], ["just ", {"b", [], ["an"]}, {"b", [], ["other"]}, " test"]}
iex(2)> :mochiweb_html.parse("<html>just <b>an</b>&nbsp;<b>other</b> test</html>")
{"html", [], ["just ", {"b", [], ["an"]}, " ", {"b", [], ["other"]}, " test"]}
```

first example, is with a regular space between </b> and <b>
Second one is with `&nbsp;`  so `...</b>&nbsp;<b>...`
As you can see, that does solve the problem....

Maybe....regex replace spaces between a closing and opening tag with &nbsp;'s ?
It's ugly...but gets the job done right ? :D

**Comment by smeevil** [comment]
how about this  : 
https://github.com/smeevil/html_sanitize_ex/commit/b702c11458025aaa0afd0df8fffb44a2929284e5

The only thing i do not understand is why the test fails even if both sides are the same ? 

![example](https://dl.dropboxusercontent.com/s/mbfhd7sbred38et/2016-02-26%20at%2023.00.png)

Do you have an explanation for that ? 
If I change the left == right to left = right it does pass....

**Comment by rrrene** [comment]
I filed an issue with mochiweb: https://github.com/mochi/mochiweb/issues/166

I'd suggest we wait until we know whether or not this is a bug. If it is not, we will have to find a solution :+1:

**Comment by rrrene** [comment]
@smeevil fixed it. Sorry this took so long, I somehow lost track of this issue. :cry: 

Version 1.0.0 contains the fix.
