### ISSUE TITLE
Experiencing high memory usage during a production complie.

### ISSUE THREAD

**Issue by zorn** [rrrene/html_sanitize_ex#41]
I use `html_sanitize_ex` in my Elixir Phoenix app. Works great.

I had an issue during a recent deploy where my compile command was getting `Killed` while it was compiling `html_sanitize_ex`. It was a repeatable failure for me. 

After some investigation it seems that the RAM usage goes way up while compiling this specific hex package. 

I do use a lower end Linode as a build server. It has 1 GB of ram with a 512 MB swap disk but other than this, it has served me well so I consider this a bug.

You can follow along my original thread about the problem here:

https://elixirforum.com/t/thoughts-on-mix-complie-getting-killed-on-my-build-machine-linode/33727/4

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.
