### ISSUE TITLE
No source code in 1.4.1 mix release

### ISSUE THREAD

**Issue by sb8244** [rrrene/html_sanitize_ex#44]
```
ls deps/html_sanitize_ex      
CHANGELOG.md        LICENSE             README.md           hex_metadata.config mix.exs
```

I don't seem to have a lib folder or any source code besides the mix.exs file. That results in:

```
iex(1)> HtmlSanitizeEx.strip_tags(File.read!("import-people.html"))
** (UndefinedFunctionError) function HtmlSanitizeEx.strip_tags/1 is undefined (module HtmlSanitizeEx is not available)
```

**Comment by rrrene** [comment]
That's strange. I am at a loss here, since it does work as expected for me:

![image](https://user-images.githubusercontent.com/311914/97262680-a9ff4b80-1821-11eb-9627-d759441c3b58.png)

Might there be anything special about your setup?

**Comment by sb8244** [comment]
Yea that's super weird. I pulled it down today and no issues. I've never seen this before....but seems like it's not related to the library. I'm confident I didn't do anything weird in my setup.
