### ISSUE TITLE
camelCase attribute transform error

### ISSUE THREAD

**Issue by mydearxym** [rrrene/html_sanitize_ex#48]
hi there ~

i am trying to do some custom sanitize logic for svg tag, but i found camelCase attribute will be transform to lowercase unexpectedly.

for example:

```elixir
iex(12)> HtmlSanitizeEx.noscrub(~s(<svg viewBox="0 0 1024" width="20px"></svg>))
"<svg viewbox=\"0 0 1024\" width=\"20px\"></svg>"
```
viewBox -> viewbox

and also, svg tag has tons of those [cameCase attruites](https://developer.mozilla.org/zh-CN/docs/Web/SVG/Attribute), this make it very hard to sanitize ...

any plan to support `Meta.allow_tag_with_these_attributes("svg", [*])` like syntax ?

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

This particular issue is due to the used HTML parser and can not be solved by this library, unfortunately.

Please feel free to re-open this issue at your discretion.
