### ISSUE TITLE
Whitespace for images

### ISSUE THREAD

**Issue by sb8244** [rrrene/html_sanitize_ex#52]
I found a bit of a tricky issue with stripping HTML -> plaintext. If I have an image separating 2 paragraphs, they are pushed right up against each other without a space. For example:

```elixir
iex(3)> HtmlSanitizeEx.strip_tags("<p>I'm a paragraph.</p><img src='xx' /><p>I'm another.</p>")                              
"I'm a paragraph.I'm another."
```

I would expect there to be a space between them. Is it best to do something like this?:

```elixir
iex(4)> "<p>I'm a paragraph.</p><img src='xx' /><p>I'm another.</p>" |> String.replace("<img", " <img") |> HtmlSanitizeEx.strip_tags()    
"I'm a paragraph. I'm another."
```

This use case (html to plaintext) might be fraught with a bunch of pitfalls that exist no matter what, but I'm just not seeing yet.

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

This particular issue is due to the used HTML parser and can not be solved by this library, unfortunately.

Please feel free to re-open this issue at your discretion.
