### ISSUE TITLE
Package unmaintained? Add another maintainer?

### ISSUE THREAD

**Issue by njwest** [rrrene/html_sanitize_ex#53]
First off, this is an awesome package, thank you @rrrene for sharing this with the world!

It appears that this this wonderful free piece of software is not actively maintained at the moment, as the last commit was over a year ago (July 2020), and minor pull requests are accumulating. I imagine this is due to René's extreme business.

I don't think there are any severe problems yet, but I'm concerned the package will begin to fail if/when breaking changes are introduced by major Elixir version upgrades and/or changes to `mochiweb 2.22.0` become necessary. It also looks like there are some nice-to-have pull requests. Does the package need another maintainer?

**Comment by rrrene** [comment]
Thx for taking an interest and the time to raise this issue. I will be thinking about this while taking you various arguments into account.
