### ISSUE TITLE
Handling of whitespace in the CSS scrubber

### ISSUE THREAD

**Issue by nwittstruck** [rrrene/html_sanitize_ex#57]
First of all thank you for the great library!

I’m trying to understand how the CSS scrubber works:  If I understand correctly, first, the [regex groups all non whitespace characters](https://github.com/rrrene/html_sanitize_ex/blob/master/lib/html_sanitize_ex/scrubber/css.ex#L158) and then checks if it’s either an allowed keyword or a measured unit.

This works fine for e.g. ```rgb(0,0,0)```, because it does not contain whitespaces. Thus, the string ```rgb(0,0,0)``` is passed to ```measured_unit?``` as is. 

However, for ```rgb(0, 0, 0)```, three calls to ```measured_unit?``` are made:

```
1. rgb(0,
2. 0,
3. 0)
```

Is this intentional? The string still gets matched, because the regex in [measured_unit?](https://github.com/rrrene/html_sanitize_ex/blob/master/lib/html_sanitize_ex/scrubber/css.ex#L213) also matches ```0```, and ```0)```. But it doesn’t really match the ```rgb(..)``` part of the regex, just the last part of the regex that is supposed to match e.g. ```5em```.

**Comment by rrrene** [comment]
I'm not sure you stated a question, but something seems like it's not working as intended.

**Comment by nwittstruck** [comment]
Yes, it seems like it. I was wondering if it's intentional that the matching happens on substrings separated by whitespace. I assume this used for a css style like ```border: 1px solid black```? In this example, it makes sense to match ```1px```, ```solid``` and ```black```separately. It breaks for ```rgb(0, 0, 0)```, which actually should not be treated the same way.

**Comment by rrrene** [comment]
Yeah, we should change that. 🤔 

If you would like to contribute a different implementation for `scrub_val/1`, feel free to open a PR :+1:

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at following up with you 😥 

Please feel free to re-open this issue at your discretion.
