### ISSUE TITLE
HTML Escaping

### ISSUE THREAD

**Issue by cschiewek** [rrrene/html_sanitize_ex#59]
Hey @rrrene,

First, thank you for the work in the lib, it's met our needs and working great!

I'm trying to understand expectations and behaviour around HTML entities.  It seems that `&`, `<`, and `>` are escaped, while others are not, even when using the `NoScrub` scrubber:

```
iex(1)> HtmlSanitizeEx.noscrub("&")
"&amp;"
iex(2)> HtmlSanitizeEx.noscrub("<")
"&lt;"
iex(3)> HtmlSanitizeEx.noscrub(">")
"&gt;"
iex(4)> HtmlSanitizeEx.noscrub("'")
"'"
iex(5)> HtmlSanitizeEx.noscrub("°") 
"°"
```

Is that intended behaviour or a bug?

**Comment by rrrene** [comment]
This is the intended behaviour. 

Did you have a different expectation?

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue.

Please feel free to re-open this issue at your discretion.
