### ISSUE TITLE
Error when using the `allow_tags_with_style_attributes` macro

### ISSUE THREAD

**Issue by rukykf** [rrrene/html_sanitize_ex#60]
When I make use of the `Meta.allow_tags_with_style_attributes` macro in my custom scrubber, I get this error message when I try to compile:

```
== Compilation error in file lib/testing_elixir_deps.ex ==
** (CompileError) lib/testing_elixir_deps.ex:59: undefined function scrub_css/1 (expected TestingElixirDeps.MyScrubber to define such a function or for it to be imported, but none are available)

** (exit) shutdown: 1
    (mix 1.14.0) lib/mix/tasks/compile.all.ex:78: Mix.Tasks.Compile.All.compile/4
    (mix 1.14.0) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.14.0) lib/mix/tasks/compile.all.ex:33: Mix.Tasks.Compile.All.run/1
    (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.0) lib/mix/tasks/compile.ex:134: Mix.Tasks.Compile.run/1
    (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (iex 1.14.0) lib/iex/helpers.ex:108: IEx.Helpers.recompile/1
    iex:17: (file)
```

Here's the code for the custom scrubber I wrote:
```
  defmodule MyScrubber do
    require HtmlSanitizeEx.Scrubber.Meta
    alias HtmlSanitizeEx.Scrubber.Meta

    # Removes any CDATA tags before the traverser/scrubber runs.
    Meta.remove_cdata_sections_before_scrub()
    Meta.strip_comments()

    Meta.allow_tags_with_style_attributes(["p", "span", "html", "body"])
    Meta.allow_tags_and_scrub_their_attributes(["b", "i"])

    Meta.strip_everything_not_covered()
  end
```

You can reproduce the error by creating and using a custom scrubber with the `Meta.allow_tags_with_style_attributes` macro.

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the html_sanitize_ex dep to

```elixir
{:html_sanitize_ex, github: "rrrene/html_sanitize_ex"}
```

Please report back if your issue is solved! 👍

**Comment by rukykf** [comment]
I'll test this out when I'm back to work next week. Thanks so much for responding so quickly.

**Comment by rukykf** [comment]
@rrrene When I tested from the `master` branch, I still was not able to allow tags with style attributes.
~There was a tiny bug which I created a Fix for in this [PR](https://github.com/rrrene/html_sanitize_ex/pull/61) which is available for your review.~

It's not exactly a bug, it's just that the code does not work if one follows the instructions in the README and the example in the `customer_scrubber_test.exs` file. 

Specifically, just using either `Meta.allow_tags_with_style_attributes` or `Meta.allow_tag_with_uri_attributes` does not work. 

In addition to allowing style or URI with `Meta.allow_tags_with_style_attributes`, I still needed to use the `Meta.allow_tags_and_scrub_their_attributes` to get the scrubber to actually allow the tag and scrub the attributes.

I updated the documentation and the `custom_scrubber_test.exs` in the PR I created here:  [PR](https://github.com/rrrene/html_sanitize_ex/pull/61)

**Comment by rrrene** [comment]
So you are saying that the original bug is fixed now (on `master`)?

**Comment by rrrene** [comment]
I am closing this since there does not seem to be an issue any more. Please re-open if this assessment is incorrect :+1:
