### ISSUE TITLE
Is there a new release?

### ISSUE THREAD

**Issue by shahryarjb** [rrrene/html_sanitize_ex#63]
Hi, before asking the question I want to thank you for all your efforts.
I saw you commited and fix some bug and added documents , but the version was released in hex.pm is for `Aug 30, 2021`.
is there possible to release new version, I want to use in my open source project and getting from hex.pm?

Thank you in advance

**Comment by rrrene** [comment]
I just released the most recent changes as version `1.4.3` to Hex :+1:
