### ISSUE TITLE
Markdown quotes  are sanitized in HtmlSanitizeEx.markdown_html/1

### ISSUE THREAD

**Issue by marschro** [rrrene/html_sanitize_ex#66]
Hi there,

so I just figured out, that Markdown quotes are sanitized.

This markdown:
```markdown
> some quote
```
should not be scrubbed to 
```
&gt;
```

I use `HtmlSanitizeEx.markdown_html/1` for sanitizing.
Same result with `HtmlSanitizeEx.basic_html/1`

Or expected behavior and I got it wrong?

kind regards!

**Comment by rrrene** [comment]
Oh, gosh ... `markdown_html/1` is supposed to take HTML from a Markdown Converter. I did not document that too well ...

https://hexdocs.pm/html_sanitize_ex/HtmlSanitizeEx.Scrubber.MarkdownHTML.html#content

Does that "solve" your problem?

**Comment by marschro** [comment]
Ha :D - then I got it wrong... 
Thanks for pointing out. I will check the scrubber...

**Comment by marschro** [comment]
Closed it, but for giving feedback - no MarkdownHTML does not work.

What I wanted to do, is, to parse markdown with your library in order to remove all html tags, that were maybe put by the user.

But the silly decision, to use `>` as marker for blockquotes causes the pain.

I checked the lib what's been the reason, and its `:mochweb_html.to_html()` that causes to (correctly) escape this single `>` to `&gt;`

## Solution for me
for sure not the most professional... but works...
```elixir
defmodule Sanitize do
  require HtmlSanitizeEx

  def strip_tags(%{"markdown" => _markdown} = attrs) do
    attrs
    |> Map.update!("markdown", &HtmlSanitizeEx.strip_tags/1)
    |> Map.update!("markdown", &heal_markdown/1)
  end

  def strip_tags(attrs), do: attrs

  defp heal_markdown(markdown) do
    markdown
    |> String.replace("&gt;", ">")
    |> String.replace("&lt;", "<")
  end
end
```

**Comment by rrrene** [comment]
Seems reasonable to me 😎

Out of curiosity: If you want to sanitize Markdown and are not converting it to HTML, what are you doing with it?

**Comment by marschro** [comment]
Hi @rrrene ,

The flow is:
- user writes markdown in texture/area. Markdown is validated, but still html can be injected in the client-side editor
- Before saving to database, I sanitize with your library. I only want the markdown to be stored not any html (bit of misuse of your lib maybe, but works perfectly fine :D) 
- When it's loaded from database, Markdown is converted to html and rendered in Phoenix as `raw()` html.
