### ISSUE TITLE
Is there any way to customize the list of accepted html tags?

### ISSUE THREAD

**Issue by asiniy** [rrrene/html_sanitize_ex#7]
Actually I think the whole interface should be changed from:

``` elixir
HtmlSanitizeEx.noscub(html)
HtmlSanitizeEx.html5(html)
```

up to

``` elixir
HtmlSanitizeEx.sanitize(html, :noscub)
HtmlSanitizeEx.sanitize(html, :html5)
HtmlSanitizeEx.sanitize(html, ~w(h1 h2 h3 div))
```

where 2nd argument either atom for using existing strategy or custom list of accepted attributes. What do you think?

**Comment by rrrene** [comment]
You can already implement what you described above using the provided DSL:

``` elixir
defmodule YourApp.YourScrubber do
  require HtmlSanitizeEx.Scrubber.Meta
  alias HtmlSanitizeEx.Scrubber.Meta

  Meta.remove_cdata_sections_before_scrub
  Meta.strip_comments

  for tag <- ~w(h1 h2 h3 div) do
    Meta.allow_tag_with_these_attributes tag, []
  end

  Meta.strip_everything_not_covered
end
```

I see your point and why you might think your `HtmlSanitizeEx.sanitize(html, ~w(h1 h2 h3 div))` example is more user-friendly. However, this clearly misses several important issues: What about attributes and attribute-specific scrubbing? What if wanted to allow links? Or styles?

Thx for raising this issue :+1: I am always open to suggestions here, but we have to think this through before making changes that have alot of implications.

What do you think?

**Comment by asiniy** [comment]
I think this works well

**Comment by sergiotapia** [comment]
@rrrene How do I use this custom scrubber module?
